version: "3"
services:
  # mongo:
  #   container_name: mongo
  #   hostname: mongo
  #   image: mongo
  #   ports:
  #     - "27017:27017"
  server:
    build: server/
    command: node ./index.js
    ports:
      - "3000:3000"
    # links:
    #   - mongo
  client:
    build: public/
    command: http-server ./ -p 8089 -c 1 --push-state
    network_mode: host
    ports:
      - "8089:8089"
    depends_on:
      - server
